#!/usr/bin/python3.5
# -*- coding: utf-8 -*-
__author__ = 'echo'
import os
import sys
args_1 = sys.argv[1]
os.rename(args_1,"test.c")
os.system("sdcc test.c ")
os.system("packihx test.ihx > test.hex")
os.system("sudo stcflash test.hex")
os.system("rm test.lk test.map test.rel test.sym test.asm test.ihx test.lst test.mem test.rst")
